### ISSUE TITLE
Extend query text to be readable

### ISSUE THREAD

**Issue by whs2k** [whs2k/loc_challenge_ai#1]
Extend or summarize the query text so that it is readable and understandable

![image](https://user-images.githubusercontent.com/29383080/37869708-0f19b138-2f93-11e8-807f-44ec68ccc374.png)

![image](https://user-images.githubusercontent.com/29383080/37869697-e2bd7e58-2f92-11e8-9fd6-15ca7aada388.png)

**Comment by mixmastamyk** [comment]
Just added the string length to the config file so now easy to change to your liking.
