### ISSUE TITLE
Create Limit for Active Queries on Jobs Page

### ISSUE THREAD

**Issue by whs2k** [whs2k/loc_challenge_ai#4]
Find way to limit the number of queries displayed on the Jobs page. Most important is to make sure that the list doesn't become too long and hard to navigate for users. Options:

- Limit Number of Queries displayed (deleting old ones) to ~10-20
- Allow users to delete Queries
- have Queries Time out after a set period of time (this option must be combined with one of the other two above, again, so the list doesn't become too unruly to navigate)

**Comment by mixmastamyk** [comment]
We could do any or all of these.  Do you have a preference?  The first one would be easy and useful for folks if not too many arrived at once, since they wouldn't have to worry about it being lost quickly.

**Comment by whs2k** [comment]
Let's go with the first one then (easiest to implement and explain); traffic should be light

**Comment by mixmastamyk** [comment]
Currently limited to 10, but can be changed with the job_list_capacity setting in the config module.

Give it a try.

**Comment by whs2k** [comment]
Looks good to me!
